maintainer       "gplv2"
maintainer_email "eedgar@zenoss"
license          "All rights reserved"
description      "Installs/Configures ZenossEnterprise"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
depends          "memcached"
depends          "erlang"
depends          "rabbitmq"
depends          "java"
depends          "yum"
depends          "apt"
depends          "ant"
depends          "maven"
depends          "build-essential"
depends          "zends"
depends          "openssh"
depends          "zenoss"
depends          "git"
depends          "subversion"
version          "0.0.2"
